import type { Prospect, Opportunity, FollowUp, DailyAnalytics, GrowthContext } from '@/types';

export const demoGrowthContext: GrowthContext = {
  id: 'demo-context',
  product_name: 'Seacho',
  one_liner: 'An AI growth employee that finds who founders should talk to today.',
  website: 'growthpilot.app',
  target_customer: 'Solo founders and small startup teams',
  industry: 'B2B SaaS / AI tools',
  keywords: ['founder tools', 'AI agents', 'outbound', 'indie hacking'],
  competitors: ['Clay', 'Apollo', 'Warmly'],
  goals: ['find_customers', 'find_investors', 'find_beta_users'],
};

export const demoProspects: Prospect[] = [
  {
    id: 'p1',
    name: 'Amara Chen',
    headline: 'Building a dev-tools startup, ex-Stripe',
    company: 'Loopstack',
    platform: 'X',
    profile_url: 'https://x.com/example',
    location: 'San Francisco, CA',
    role: 'Founder & CEO',
    company_size: '1-10',
    stage: 'Pre-seed',
    fit_score: 92,
    pain_points: ['Manual outbound eating her mornings', 'No time for investor updates'],
    mutual_interests: ['Building in public', 'AI agents'],
    recent_activity: 'Posted about spending 2 hours/day on manual LinkedIn outreach',
    why_relevant: 'Explicitly complained about the exact problem Seacho solves, this week.',
    suggested_approach: 'Comment on her post with a specific tip, then follow up with a DM after she engages.',
    pipeline_stage: 'new',
    tags: ['warm', 'founder'],
  },
  {
    id: 'p2',
    name: 'Daniel Osei',
    headline: 'Angel investor, 40+ pre-seed checks',
    company: 'Kaleo Ventures',
    platform: 'LinkedIn',
    location: 'London, UK',
    role: 'Investor',
    company_size: 'N/A',
    stage: 'N/A',
    fit_score: 78,
    pain_points: [],
    mutual_interests: ['African founder ecosystem', 'AI tooling'],
    recent_activity: 'Shared an article on the rise of solo-founder SaaS',
    why_relevant: 'Actively invests in solo-founder AI tools and has backed 2 similar products.',
    suggested_approach: 'Connect first with a short personalized note referencing his article.',
    pipeline_stage: 'commented',
    tags: ['investor'],
    last_contact_date: new Date(Date.now() - 86400000 * 3).toISOString(),
    next_follow_up: new Date(Date.now() + 86400000 * 2).toISOString().slice(0, 10),
  },
  {
    id: 'p3',
    name: 'Priya Nair',
    headline: 'Indie hacker, building 3 microsaas products',
    company: 'Solo Labs',
    platform: 'X',
    location: 'Bangalore, India',
    role: 'Founder',
    company_size: '1',
    stage: 'Bootstrapped',
    fit_score: 85,
    pain_points: ['Wants beta testers for a new product'],
    mutual_interests: ['Building in public', 'No-funding founders'],
    recent_activity: 'Asked her followers for beta testers this morning',
    why_relevant: 'Fits the "founders who need beta users" segment perfectly, and is likely to reciprocate.',
    suggested_approach: 'Offer to beta test her product first, then introduce Seacho naturally.',
    pipeline_stage: 'new',
    tags: ['beta-swap'],
  },
  {
    id: 'p4',
    name: 'Marcus Webb',
    headline: 'Growth lead at a Series A startup',
    company: 'Fenwick',
    platform: 'LinkedIn',
    location: 'Austin, TX',
    role: 'Head of Growth',
    company_size: '50-200',
    stage: 'Series A',
    fit_score: 61,
    pain_points: [],
    mutual_interests: ['Growth experiments'],
    recent_activity: 'Commented on outbound automation trends',
    why_relevant: 'Adjacent audience — may be a customer champion inside a larger team.',
    suggested_approach: 'Low priority — light engagement only.',
    pipeline_stage: 'new',
    tags: [],
  },
];

export const demoOpportunities: Opportunity[] = [
  { id: 'o1', prospect: demoProspects[0], recommended_action: 'comment_first', reason: 'Posted about the exact problem you solve, 4 hours ago.', surfaced_on: new Date().toISOString().slice(0, 10), dismissed: false },
  { id: 'o2', prospect: demoProspects[2], recommended_action: 'send_dm', reason: 'Actively asking for beta testers right now — high response likelihood.', surfaced_on: new Date().toISOString().slice(0, 10), dismissed: false },
  { id: 'o3', prospect: demoProspects[1], recommended_action: 'follow_up_tomorrow', reason: 'Commented 3 days ago, no reply yet. Good time to nudge.', surfaced_on: new Date().toISOString().slice(0, 10), dismissed: false },
  { id: 'o4', prospect: demoProspects[3], recommended_action: 'connect_first', reason: 'Adjacent audience, worth a light-touch connection.', surfaced_on: new Date().toISOString().slice(0, 10), dismissed: false },
];

export const demoFollowUps: FollowUp[] = [
  {
    id: 'f1',
    prospect: demoProspects[1],
    suggested_message: "Hey Daniel — following up on my note last week. Curious what you made of the traction stats I sent over?",
    priority: 'high',
    due_date: new Date().toISOString().slice(0, 10),
    completed: false,
  },
];

export const demoAnalytics: DailyAnalytics[] = Array.from({ length: 7 }).map((_, i) => ({
  day: new Date(Date.now() - 86400000 * (6 - i)).toISOString().slice(0, 10),
  prospects_discovered: 6 + Math.round(Math.random() * 6),
  outreach_drafts_created: 3 + Math.round(Math.random() * 4),
  replies_tracked: Math.round(Math.random() * 3),
  meetings_booked: Math.round(Math.random() * 1),
  customers_closed: 0,
}));
